### ISSUE TITLE
Question: Time scale/span for SPEI1, SPEI3, SPEI6 etc.

### ISSUE THREAD

**Issue by Appleweier** [martinvonk/SPEI#26]
What is the time scale of the calculated SPEI?

**Comment by martinvonk** [comment]
Hi @Appleweier,

Thank you for your issue. Can you maybe clarify a bit what you mean by the time scale? 

In general, SPEI uses [Pandas (time) Series](https://pandas.pydata.org/docs/user_guide/timeseries.html) to do the time management because it is a very powerfull tool to handle timeseries. With Pandas Series you can easily sum over different time scales using the `series.rolling(time_scale).sum()` method. Everything is nicely documented in the [example notebooks](https://github.com/martinvonk/SPEI/tree/main/doc/examples).

**Comment by Appleweier** [comment]
Thanks for your reply, SPEI can be calculated on different time scales as needed, common time scales include 1 month, 3 months, 6 months, 12 months and 24 months, each time scale provides different drought information. After reading the example notebooks, I understand that the SPEI is calculated in the example notebooks for the one-month time scale, right?（f = 30  # days
）

**Comment by martinvonk** [comment]
No, you can calculate the SPEI over whatever time span you require through Pandas. So, if you require the 1 month time span you would sum your series like so:  `series.rolling("30D").sum()`. And for the other time spans you would just provide another time window;

- SPEI3: `series.rolling("90D").sum()`
- SPEI6: `series.rolling("180D").sum()`
- etcetera (I don't know what the convention of rounding months to days is since months can have various days.

In the example notebooks there are also examples where the SPEI is calculated over a 3 month interval.

**Comment by Appleweier** [comment]
Thank you for your reply, I got it.
